### ISSUE TITLE
client.get_chart fails

### ISSUE THREAD

**Issue by hithomasmorelli** [browniebroke/deezer-python#132]
Discovered when testing/fixing #127 

Calling `client.get_chart()` results in the following stack trace:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/deezer-python/deezer/client.py", line 213, in get_chart
    return self.get_object(
  File "/deezer-python/deezer/client.py", line 205, in get_object
    return self._process_json(json, parent)
  File "/deezer-python/deezer/client.py", line 120, in _process_json
    value = self._process_json(value, parent)
  File "/deezer-python/deezer/client.py", line 115, in _process_json
    return [self._process_json(i, parent) for i in item["data"]]
  File "/deezer-python/deezer/client.py", line 115, in <listcomp>
    return [self._process_json(i, parent) for i in item["data"]]
  File "/deezer-python/deezer/client.py", line 126, in _process_json
    object_class = self.objects_types[result["type"]]
KeyError: 'podcast'
```

Will attempt to fix and introduce a PR

**Comment by hithomasmorelli** [comment]
I suspect that Deezer has changed their API responses a bit as the tests for this that use the cassettes don't fail

**Comment by hithomasmorelli** [comment]
right, so this is caused by `podcast` not being in `Client.objects_types`. I'll create a new `resources.Playlist` class and introduce a few Playlist methods when fixing this.
