### ISSUE TITLE
How to get the music you currently listen to?

### ISSUE THREAD

**Issue by adlgrbz** [browniebroke/deezer-python#87]
How to get the music the user is currently listening to?

**Comment by browniebroke** [comment]
Hum, not sure if that's possible. This library is just a wrapper around [the official REST API](https://developers.deezer.com/api/), and I don't see anything listed there regarding such a capability. 

If you find something I've missed, I'd be happy to help you get to the Python function in the library.

**Comment by adlgrbz** [comment]
Thanks!

Does this help?
https://stackoverflow.com/questions/30468994/deezer-api-users-currently-playing-song

**Comment by adlgrbz** [comment]
https://developers.deezer.com/api/user/history

**Comment by browniebroke** [comment]
I see. This isn't implemented currently, but I would imagine you could get it with something like this:

```python
import deezer
client = deezer.Client()
user = client.get_user(USER_ID)

# get user history:
user.get_relation("history")
# OR
user.get_relation("me/history")
```

From a quick test it doesn't work currently, you might have to pass the `access_token` to the `Client` class with `deezer.Client(access_token=USER_ACCESS_TOKEN)`.

**Comment by adlgrbz** [comment]
How to obtain `USER_ACCESS_TOKEN` ?

**Comment by adlgrbz** [comment]
Hey, 
I got an `USER_ACCESS_TOKEN` but I get an error...

Deezer profile: https://www.deezer.com/tr/profile/3508485404

```python
import deezer


client = deezer.Client(
    access_token="0123456789abcdefgh"
)

user = client.get_user("3508485404")
history = user.get_relation("history")

print(history)
```
```
Traceback (most recent call last):
  File "/home/adil/Masaüstü/d_e_n_e_m_e_1.py", line 10, in <module>
    print(user.get_relation("history"))
  File "/home/adil/.local/lib/python3.7/site-packages/deezer/resources.py", line 52, in get_relation
    return self.client.get_object(self.type, self.id, relation, self, **kwargs)
  File "/home/adil/.local/lib/python3.7/site-packages/deezer/client.py", line 185, in get_object
    object_t, object_id
ValueError: API request return error for object: user id: 3508485404
```

**Comment by adlgrbz** [comment]
**?**

**Comment by browniebroke** [comment]
As far as I can see, there is no way to get the current playing song. Songs are pushed to the user listening history once they finsihed/skipped to the next song.

I've added a method for that nevertheless. It requires a special permission `listening_history` to be granted when requesting the token.
